<?php
/**
 * Government Resources Data for all 95 Tennessee counties.
 *
 * Each county key maps to an array of resource type => URL.
 * Resource types: assessor, trustee, register, chancery, circuit, thda
 *
 * URLs were researched and verified April 2026.
 * If a URL could not be verified for a specific office, it is omitted.
 */

function tcfh_get_gov_resources( $county_key ) {
    static $data = null;

    if ( $data === null ) {
        $thda = 'https://thda.org';

        $data = [
            'Anderson' => [
                'assessor' => 'https://andersoncountytn.gov/assessor-of-property/',
                'trustee'  => 'https://andersoncountytn.gov/trustee/',
                'register' => 'https://andersoncountytn.gov/register-of-deeds/',
                'chancery' => 'https://andersoncountyclerkandmaster.com/',
                'circuit'  => 'https://andersoncountytn.gov/circuit-court-clerk/',
                'thda'     => $thda,
            ],
            'Bedford' => [
                'assessor' => 'https://www.bedfordcountytn.gov/government/property_assessor/index.php',
                'trustee'  => 'https://www.bedfordcountytn.gov/government/trustee/index.php',
                'register' => 'https://www.bedfordcountytn.gov/government/register_of_deeds/index.php',
                'chancery' => 'https://www.bedfordcountytn.gov/courts/chancery_court/index.php',
                'circuit'  => 'https://www.bedfordcountytn.gov/courts/circuit_court_clerk.php',
                'thda'     => $thda,
            ],
            'Benton' => [
                'assessor' => 'https://www.bentoncountytn.gov/assessor_of_property.html',
                'trustee'  => 'https://www.bentoncountytn.gov/trustee.html',
                'chancery' => 'https://www.bentoncountytn.gov/clerk_master.html',
                'circuit'  => 'https://www.bentoncountytn.gov/circuit_court_clerk.html',
                'thda'     => $thda,
            ],
            'Bledsoe' => [
                'assessor' => 'https://bledsoetn.com/',
                'trustee'  => 'https://bledsoetn.com/',
                'register' => 'https://bledsoetn.com/',
                'chancery' => 'https://bledsoetn.com/chancery-court/',
                'thda'     => $thda,
            ],
            'Blount' => [
                'assessor' => 'https://www.blounttn.gov/317/Property-Assessor',
                'trustee'  => 'https://www.blounttn.gov/322/Trustee',
                'register' => 'https://www.blounttn.gov/321/Register-of-Deeds',
                'chancery' => 'https://www.blounttn.gov/308/Clerk-Masters-Office',
                'circuit'  => 'https://www.blounttn.gov/2023/Circuit-Court-Clerk',
                'thda'     => $thda,
            ],
            'Bradley' => [
                'assessor' => 'https://bradleycountytn.gov/county-government/assessor-of-property/',
                'trustee'  => 'https://bradleycountytn.gov/county-government/trustee/',
                'register' => 'https://bradleycountytn.gov/county-government/register-of-deeds/',
                'chancery' => 'https://bradleychancery.org/',
                'circuit'  => 'https://bradleycountytn.gov/county-government/circuit-criminal-court-clerk/',
                'thda'     => $thda,
            ],
            'Campbell' => [
                'assessor' => 'https://campbellcountytn.gov/elected-officials/property-assessor/',
                'trustee'  => 'https://campbellcountytn.gov/elected-officials/trustee/',
                'register' => 'https://campbellcountytn.gov/elected-officials/register-of-deeds/',
                'chancery' => 'https://campbellcountytn.gov/courts/chancery-court/',
                'circuit'  => 'https://www.campbellcountycircuitcourt.com/',
                'thda'     => $thda,
            ],
            'Cannon' => [
                'assessor' => 'https://cannoncountytn.gov/property-assessor/',
                'trustee'  => 'https://cannoncountytn.gov/trustee/',
                'register' => 'https://cannoncountytn.gov/registrar/',
                'chancery' => 'https://cannoncountytn.gov/courts/',
                'circuit'  => 'https://cannoncountytn.gov/courts/',
                'thda'     => $thda,
            ],
            'Carroll' => [
                'assessor' => 'https://carrollcountytn.gov/',
                'trustee'  => 'https://carrollcountytn.gov/',
                'register' => 'https://carrollcountytn.gov/',
                'chancery' => 'https://carrollcountytn.gov/',
                'circuit'  => 'https://carrollcountytn.gov/circuit_court.html',
                'thda'     => $thda,
            ],
            'Carter' => [
                'assessor' => 'https://www.cartercountytn.gov/government/elected_officials/assessor_of_property.php',
                'trustee'  => 'https://www.cartercountytn.gov/government/elected_officials/county_trustee.php',
                'register' => 'https://www.cartercountytn.gov/government/elected_officials/register_of_deeds.php',
                'chancery' => 'https://www.cartercountytn.gov/government/elected_officials/clerk___master.php',
                'circuit'  => 'https://www.cartercountytn.gov/government/elected_officials/circuit_court_clerk.php',
                'thda'     => $thda,
            ],
            'Cheatham' => [
                'assessor' => 'https://www.cheathamcountytn.gov/assessor_of_property.html',
                'trustee'  => 'https://www.cheathamcountytn.gov/trustee.html',
                'register' => 'https://www.cheathamcountytn.gov/register_of_deeds.html',
                'chancery' => 'https://www.cheathamcountytn.gov/court_chancery.html',
                'circuit'  => 'https://www.cheathamcountycircuitcourt.com/',
                'thda'     => $thda,
            ],
            'Chester' => [
                'assessor' => 'https://chestercountytn.org/assessor_of_property.html',
                'trustee'  => 'https://chestercountytn.org/trustee.html',
                'register' => 'https://chestercountytn.org/register_of_deeds.html',
                'chancery' => 'https://chestercountytn.org/chancery_court_clerk.html',
                'circuit'  => 'https://chestercountytn.org/circuit_court_clerk.html',
                'thda'     => $thda,
            ],
            'Claiborne' => [
                'assessor' => 'https://claibornecountytn.gov/countyoffices/county-officials/property-assessor/',
                'trustee'  => 'https://claibornecountytn.gov/countyoffices/county-officials/trustee/',
                'register' => 'https://claibornecountytn.gov/countyoffices/county-officials/register-of-deeds/',
                'chancery' => 'https://claibornecountytn.gov/countyoffices/law-justice/chancery-court/',
                'circuit'  => 'https://claibornecountytn.gov/countyoffices/law-justice/circuit-court-sessions-court/',
                'thda'     => $thda,
            ],
            'Clay' => [
                'assessor' => 'https://www.claycountytngov.com/assessorofproperty',
                'trustee'  => 'https://www.claycountytngov.com/trustee',
                'register' => 'https://www.claycountytngov.com/registerofdeeds',
                'chancery' => 'https://www.claycountytngov.com/chancerycourt',
                'circuit'  => 'https://www.claycountytngov.com/circuitcourtclerk',
                'thda'     => $thda,
            ],
            'Cocke' => [
                'assessor' => 'https://www.cockecountytn.gov/assessor-of-property',
                'trustee'  => 'https://www.cockecountytn.gov/trustee',
                'register' => 'https://www.cockecountytn.gov/register-of-deeds',
                'chancery' => 'https://www.cockecountytn.gov/clerk-master',
                'circuit'  => 'https://www.cockecountytn.gov/circuit-court-clerk',
                'thda'     => $thda,
            ],
            'Coffee' => [
                'assessor' => 'https://www.coffeecountytn.gov/209/Property-Assessor',
                'trustee'  => 'https://www.coffeecountytn.gov/211/Trustee',
                'register' => 'https://www.coffeecountyregisterofdeeds.com/',
                'chancery' => 'https://coffeecountytn.gov/161/Chancery-Court',
                'circuit'  => 'https://www.coffeecountytn.gov/337/Circuit-Court-Clerk',
                'thda'     => $thda,
            ],
            'Crockett' => [
                'assessor' => 'https://www.crockettcountytn.com/government',
                'trustee'  => 'https://www.crockettcountytn.com/government',
                'register' => 'https://www.crockettcountytn.com/government',
                'chancery' => 'https://www.crockettcountytn.com/government',
                'circuit'  => 'https://www.crockettcountytn.com/government',
                'thda'     => $thda,
            ],
            'Cumberland' => [
                'assessor' => 'https://cumberlandcountytn.gov/directory/assessor-of-property/',
                'trustee'  => 'https://cumberlandcountytn.gov/directory/trustee/',
                'register' => 'https://cumberlandcountytn.gov/directory/register-of-deeds/',
                'chancery' => 'https://cumberlandcountytn.gov/directory/clerk-master/',
                'circuit'  => 'https://cumberlandcountytn.gov/directory/circuit-court/',
                'thda'     => $thda,
            ],
            'Davidson' => [
                'assessor' => 'https://www.nashville.gov/departments/assessor',
                'trustee'  => 'https://www.nashville.gov/departments/trustee',
                'register' => 'https://www.nashville.gov/departments/register-deeds',
                'chancery' => 'https://chanceryclerkandmaster.nashville.gov/',
                'circuit'  => 'https://circuitclerk.nashville.gov/',
                'thda'     => $thda,
            ],
            'Decatur' => [
                'assessor' => 'https://decaturcountytn.gov/departments/',
                'trustee'  => 'https://www.decatur.tennesseetrustee.org/',
                'register' => 'https://decaturcountytn.gov/departments/',
                'chancery' => 'https://dcchancery.com/',
                'circuit'  => 'https://decaturcountytn.gov/departments/',
                'thda'     => $thda,
            ],
            'DeKalb' => [
                'assessor' => 'https://www.dekalbtennessee.com/property-assessor.html',
                'trustee'  => 'https://dekalb.tennesseetrustee.org/',
                'register' => 'https://www.dekalbtennessee.com/register-of-deeds.html',
                'chancery' => 'https://www.dekalbtennessee.com/clerk-and-master.html',
                'circuit'  => 'https://www.dekalbtennessee.com/circuit-court-clerk.html',
                'thda'     => $thda,
            ],
            'Dickson' => [
                'assessor' => 'https://www.dicksoncountytn.gov/assessor.html',
                'trustee'  => 'https://www.dicksoncountytn.gov/trustee.html',
                'register' => 'https://www.dicksoncountytn.gov/register_of_deeds.html',
                'chancery' => 'https://dicksoncountytn.gov/chancery_court.html',
                'circuit'  => 'https://dicksoncountytn.gov/circuit_court.html',
                'thda'     => $thda,
            ],
            'Dyer' => [
                'assessor' => 'https://www.dyercounty.com/Dyer-County-Offices',
                'trustee'  => 'https://dyer.tennesseetrustee.org/',
                'register' => 'https://www.dyercounty.com/Dyer-County-Offices',
                'chancery' => 'https://dyercountychancery.com/',
                'circuit'  => 'https://www.dyercounty.com/Dyer-County-Offices',
                'thda'     => $thda,
            ],
            'Fayette' => [
                'assessor' => 'https://fayettetn.us/departments/assessor/',
                'trustee'  => 'https://fayette.tennesseetrustee.org/',
                'register' => 'https://fayettetn.us/departments/register/',
                'chancery' => 'https://fayettetn.us/departments/chancery-court/',
                'circuit'  => 'https://fayettetn.us/departments/circuit-general-sessions-court/',
                'thda'     => $thda,
            ],
            'Fentress' => [
                'assessor' => 'https://fentresscountytn.gov/property-assessor/',
                'trustee'  => 'https://fentresscountytn.gov/trustee/',
                'register' => 'https://fentresscountytn.gov/register-of-deeds/',
                'chancery' => 'https://fentresscountytn.gov/clerk-and-master/',
                'circuit'  => 'https://fentresscountytn.gov/circuit-court-clerk/',
                'thda'     => $thda,
            ],
            'Franklin' => [
                'assessor' => 'https://franklincotn.us/property_assessor.html',
                'trustee'  => 'https://franklin.tennesseetrustee.org/',
                'register' => 'https://franklincotn.us/law_justice.html',
                'chancery' => 'https://franklincountychancerycourt.org/',
                'circuit'  => 'https://franklincountycircuitcourtclerk.org/',
                'thda'     => $thda,
            ],
            'Gibson' => [
                'assessor' => 'https://gibsontn.org/county-government/property-assessor',
                'trustee'  => 'https://gibsontn.org/county-government/trustee-s-office',
                'register' => 'https://gibsontn.org/county-government/register-of-deeds',
                'chancery' => 'https://gibsontn.org/county-courts/chancery',
                'circuit'  => 'https://gibsontn.org/county-courts/circuit',
                'thda'     => $thda,
            ],
            'Giles' => [
                'assessor' => 'https://gilescountytn.gov/assessor/',
                'trustee'  => 'https://gilescountytn.gov/trustee/',
                'register' => 'https://gilescountytn.gov/register/',
                'chancery' => 'https://gilescountytn.gov/courts-2/clerk-master/',
                'circuit'  => 'https://gilescountytn.gov/courts-2/circuit-court/',
                'thda'     => $thda,
            ],
            'Grainger' => [
                'assessor' => 'https://www.graingercountytn.com/county-officials/assessor/',
                'trustee'  => 'https://www.graingercountytrustee.com/',
                'register' => 'https://www.graingercountytn.com/county-officials/register-of-deeds/',
                'chancery' => 'https://www.graingercountytn.com/county-officials/clerk-master/',
                'circuit'  => 'https://www.graingercourts.com/',
                'thda'     => $thda,
            ],
            'Greene' => [
                'assessor' => 'https://www.greenecountytngov.com/property-assessor/',
                'trustee'  => 'https://www.greenecountytngov.com/trustee/',
                'register' => 'https://www.greenecountytngov.com/register-of-deeds/',
                'chancery' => 'https://www.greenecountytngov.com/clerk-master-office/',
                'circuit'  => 'https://www.greenecountytngov.com/circuit-court-clerks-office/',
                'thda'     => $thda,
            ],
            'Grundy' => [
                'assessor' => 'https://www.grundycountytn.net/officials/',
                'trustee'  => 'https://grundycountytrustee.com/',
                'register' => 'https://www.grundycountytn.net/officials/',
                'chancery' => 'https://www.grundycountytn.net/officials/',
                'circuit'  => 'https://www.grundycountytn.net/officials/',
                'thda'     => $thda,
            ],
            'Hamblen' => [
                'assessor' => 'https://www.hamblencountytn.gov/assessor-of-property/',
                'trustee'  => 'https://www.hamblencountytn.gov/county-trustee/',
                'register' => 'https://www.hamblencountytn.gov/register-of-deeds/',
                'chancery' => 'https://www.hamblencountychancery.org/',
                'circuit'  => 'https://www.hamblencountytn.gov/circuit-court-and-general-sessions-court/',
                'thda'     => $thda,
            ],
            'Hamilton' => [
                'assessor' => 'https://assessor.hamiltontn.gov/',
                'trustee'  => 'https://www.hamiltontn.gov/Trustee.aspx',
                'register' => 'https://register.hamiltontn.gov/',
                'chancery' => 'https://www.hamiltontn.gov/Courts.aspx',
                'circuit'  => 'https://www.hamiltontnclerk.com/',
                'thda'     => $thda,
            ],
            'Hancock' => [
                'assessor' => 'https://hancockcountytn.com/local_public_service_directory/assessor_of_property.php',
                'trustee'  => 'https://hancockcountytn.com/local_public_service_directory/trustee.php',
                'register' => 'https://www.hancockcountytn.com/local_public_service_directory/register_of_deeds.php',
                'chancery' => 'https://www.hancockcountytn.com/local_public_service_directory/clerk_and_master.php',
                'circuit'  => 'https://hancockcountytn.com/local_public_service_directory/circuit_court_clerk.php',
                'thda'     => $thda,
            ],
            'Hardeman' => [
                'assessor' => 'https://hardemancounty.org/departments/assessor-of-property',
                'trustee'  => 'https://hardeman.tennesseetrustee.org/',
                'register' => 'https://hardemancounty.org/departments/registers-office',
                'chancery' => 'https://hardemancounty.org/departments/chancery-court-clerk',
                'circuit'  => 'https://hardemancounty.org/departments/circuit-court-clerk',
                'thda'     => $thda,
            ],
            'Hardin' => [
                'assessor' => 'https://www.hardincogov.com/departments/',
                'trustee'  => 'https://www.hardincogov.com/hardin-county-trustee/',
                'register' => 'https://www.hardincogov.com/register-of-deeds-office/',
                'chancery' => 'https://www.hardincogov.com/hardin-county-chancery-court-clerk-and-master/',
                'circuit'  => 'https://www.hardincogov.com/circuit-clerk/',
                'thda'     => $thda,
            ],
            'Hawkins' => [
                'assessor' => 'https://www.hawkinscountytn.gov/property_assessor.html',
                'trustee'  => 'https://www.hawkinscountytn.gov/trustee.html',
                'register' => 'https://www.hawkinscountytn.gov/register_of_deeds.html',
                'chancery' => 'https://www.hawkinscountytn.gov/chancery_court_clerk_master.html',
                'circuit'  => 'https://www.hawkinscountytn.gov/circuit_court_clerk.html',
                'thda'     => $thda,
            ],
            'Haywood' => [
                'assessor' => 'https://haywoodtn.gov/property-assessor/',
                'trustee'  => 'https://haywoodtn.gov/trustee/',
                'register' => 'https://haywoodtn.gov/register-of-deeds/',
                'chancery' => 'https://haywoodtn.gov/government/court-systems/chancery-court/',
                'circuit'  => 'https://haywoodtn.gov/government/court-systems/court-clerks-office/',
                'thda'     => $thda,
            ],
            'Henderson' => [
                'assessor' => 'https://www.hendersoncountytn.gov/en-US/property-assessor-597ab3ed',
                'trustee'  => 'https://www.hendersoncountytn.gov/en-US/trustee-41ca749a',
                'register' => 'https://www.hendersoncountytn.gov/en-US/register-of-deeds-631ebb7b',
                'chancery' => 'https://www.hendersoncountytn.gov/en-US/clerk-master-chancery-court-e8e50247',
                'circuit'  => 'https://www.hendersoncountytn.gov/en-US/circuit-clerk-general-sessions-court-bf44d3c8',
                'thda'     => $thda,
            ],
            'Henry' => [
                'assessor' => 'https://henrycountytn.org/assessor-of-property/',
                'trustee'  => 'https://henrycountytrustee.com/',
                'register' => 'https://henrycountytn.org/register-of-deeds/',
                'chancery' => 'https://www.henrycountychancerycourt.com/',
                'circuit'  => 'https://www.henrycountycourt.net/',
                'thda'     => $thda,
            ],
            'Hickman' => [
                'assessor' => 'https://hickmancountytn.gov/departments/administrative-offices',
                'trustee'  => 'https://www.hickman.tennesseetrustee.org/',
                'register' => 'https://hickmancountytn.gov/departments/administrative-offices',
                'chancery' => 'https://hickmancountytn.gov/departments/law-court-services',
                'circuit'  => 'https://hickmancountytn.gov/departments/law-court-services',
                'thda'     => $thda,
            ],
            'Houston' => [
                'assessor' => 'https://www.explorehoustoncountytn.com/government/property-assessor/',
                'trustee'  => 'https://www.explorehoustoncountytn.com/government/trustee/',
                'register' => 'https://www.explorehoustoncountytn.com/government/register-of-deeds/',
                'chancery' => 'https://www.explorehoustoncountytn.com/courts/chancery-court/',
                'thda'     => $thda,
            ],
            'Humphreys' => [
                'assessor' => 'https://www.humphreystn.com/property_assessor.html',
                'trustee'  => 'https://www.humphreyscountytn.gov/trustee.html',
                'register' => 'https://www.humphreyscountytn.gov/register_of_deeds.html',
                'chancery' => 'https://www.humphreystn.com/clerk_and_master.html',
                'circuit'  => 'https://www.humphreyscountytn.gov/circuit_court_clerk.html',
                'thda'     => $thda,
            ],
            'Jackson' => [
                'assessor' => 'https://www.jacksoncotn.com/countydepartments.php',
                'trustee'  => 'https://jackson.tennesseetrustee.org/',
                'register' => 'https://www.jacksoncotn.com/countydepartments.php',
                'chancery' => 'https://www.jacksoncotn.com/countydepartments.php',
                'circuit'  => 'https://www.jacksoncotn.com/countydepartments.php',
                'thda'     => $thda,
            ],
            'Jefferson' => [
                'assessor' => 'https://jeffersoncountytn.gov/property-assessor/',
                'trustee'  => 'https://jeffersoncountytn.gov/county-trustee/',
                'register' => 'https://jeffersoncountytn.gov/register-of-deeds/',
                'chancery' => 'https://jeffersoncountytn.gov/chancery-court/',
                'circuit'  => 'https://www.jeffersoncircuit.com/',
                'thda'     => $thda,
            ],
            'Johnson' => [
                'assessor' => 'https://www.johnsoncountytn.gov/administrative-offices',
                'trustee'  => 'https://www.johnson.tennesseetrustee.org/',
                'register' => 'https://www.johnsoncountytn.gov/administrative-offices',
                'chancery' => 'https://johnsoncountytnchancerycourt.info/',
                'circuit'  => 'https://www.johnsoncountytn.gov/county-officials',
                'thda'     => $thda,
            ],
            'Knox' => [
                'assessor' => 'https://www.knoxcounty.org/property/',
                'trustee'  => 'https://trustee.knoxcounty.org/',
                'register' => 'https://rod.knoxcounty.org/',
                'chancery' => 'https://www.knoxcounty.org/chancery/court_offices.php',
                'circuit'  => 'https://www.knoxcounty.org/circuit/clerk_functions.php',
                'thda'     => $thda,
            ],
            'Lake' => [
                'assessor' => 'https://lakecountytn.gov/government/assessor-of-property',
                'trustee'  => 'https://lakecountytn.gov/government/trustee',
                'register' => 'https://lakecountytn.gov/government/register-of-deeds',
                'chancery' => 'https://lakecountytn.gov/government/courts/chancery-court',
                'circuit'  => 'https://lakecountytn.gov/government/courts/circuit',
                'thda'     => $thda,
            ],
            'Lauderdale' => [
                'assessor' => 'https://lauderdalecountytn.org/our-county/government/',
                'trustee'  => 'https://lauderdale.tennesseetrustee.org/',
                'register' => 'https://lauderdalecountytn.org/our-county/government/',
                'chancery' => 'https://lauderdalecountytn.org/our-county/government/',
                'circuit'  => 'https://lauderdalecountytn.org/our-county/government/',
                'thda'     => $thda,
            ],
            'Lawrence' => [
                'assessor' => 'https://lawrencecountytn.gov/government/departments/assessor-of-property/',
                'trustee'  => 'https://lawrencecountytn.gov/government/departments/trustee/',
                'register' => 'https://lawrencecountytn.gov/government/departments/register-of-deeds/',
                'chancery' => 'https://lawrencecountytn.gov/government/departments/clerk-master/',
                'circuit'  => 'https://lawrencecountytn.gov/government/departments/circuit-court-clerk/',
                'thda'     => $thda,
            ],
            'Lewis' => [
                'assessor' => 'https://www.lewiscountytn.com/property-assessor',
                'trustee'  => 'https://www.lewiscountytn.com/trustee',
                'register' => 'https://www.lewiscountytn.com/register-of-deeds',
                'chancery' => 'https://www.lewiscountytn.com/clerk-master',
                'circuit'  => 'https://www.lewiscountytn.com/circuit-court-clerk',
                'thda'     => $thda,
            ],
            'Lincoln' => [
                'assessor' => 'https://www.lincolncountytn.gov/business_detail_T8_R9.php',
                'trustee'  => 'https://www.lincolncountytn.gov/county_directory/county_offices.php',
                'register' => 'https://www.lincolncountytn.gov/business_detail_T8_R8.php',
                'chancery' => 'https://www.lincolncountytn.gov/business_detail_T8_R24.php',
                'circuit'  => 'https://www.lincolncountytn.gov/business_detail_T8_R12.php',
                'thda'     => $thda,
            ],
            'Loudon' => [
                'assessor' => 'https://loudoncountyassessor.org/',
                'trustee'  => 'https://www.loudoncounty-tn.gov/government/Trustee.php',
                'register' => 'https://www.loudoncounty-tn.gov/government/RegisterOfDeeds.php',
                'chancery' => 'https://www.loudoncountychancery.com/',
                'circuit'  => 'https://www.loudoncountycircuitcourt.com/',
                'thda'     => $thda,
            ],
            'Macon' => [
                'assessor' => 'https://www.maconcountytn.gov/government/property_assessor.php',
                'trustee'  => 'https://maconcountytn.gov/government/trustee.php',
                'register' => 'https://www.maconcountytn.gov/government/register_of_deeds/index.php',
                'chancery' => 'https://maconcountytn.gov/visitors/courts/chancery_court.php',
                'circuit'  => 'https://maconcircuitcourt.com/',
                'thda'     => $thda,
            ],
            'Madison' => [
                'assessor' => 'https://www.madisoncountytn.gov/90/Assessor-of-Property',
                'trustee'  => 'https://madisoncountytn.gov/120/Trustee',
                'register' => 'https://madisoncountytn.gov/118/Register-of-Deeds',
                'chancery' => 'https://madisoncountychancery.com/',
                'circuit'  => 'https://www.madisoncountytn.gov/78/Circuit-Court',
                'thda'     => $thda,
            ],
            'Marion' => [
                'assessor' => 'https://marioncountytn.net/services',
                'trustee'  => 'https://www.marion.tennesseetrustee.org/',
                'register' => 'https://marioncountytn.net/services',
                'chancery' => 'https://marioncountytn.net/court',
                'circuit'  => 'https://marioncountytn.net/court',
                'thda'     => $thda,
            ],
            'Marshall' => [
                'assessor' => 'https://www.marshallcountytn.gov/assessor-of-property',
                'trustee'  => 'https://www.marshallcountytn.gov/trustee-s-office',
                'register' => 'https://marshallcountytn.gov/register-of-deeds',
                'chancery' => 'https://www.marshallcountytn.gov/clerk-master',
                'circuit'  => 'https://www.marshallcountytn.gov/circuit-court-clerk',
                'thda'     => $thda,
            ],
            'Maury' => [
                'assessor' => 'https://www.maurycounty-tn.gov/203/Assessor',
                'trustee'  => 'https://www.maurycounty-tn.gov/327/Trustee',
                'register' => 'https://www.maurycounty-tn.gov/155/Register-of-Deeds',
                'chancery' => 'https://www.maurycounty-tn.gov/210/Clerk-Master',
                'circuit'  => 'https://www.maurycounty-tn.gov/206/Circuit-Court',
                'thda'     => $thda,
            ],
            'McMinn' => [
                'assessor' => 'https://www.mcminncountytn.gov/assessor_of_property.html',
                'trustee'  => 'https://www.mcminncountytn.gov/county_trustee.html',
                'register' => 'https://www.mcminncountytn.gov/register_of_deeds.html',
                'chancery' => 'https://www.mcminncountytn.gov/clerk_master.html',
                'circuit'  => 'https://www.mcminncountytn.gov/circuit_court_clerk.html',
                'thda'     => $thda,
            ],
            'McNairy' => [
                'assessor' => 'https://www.mcnairycountytn.org/property-assessor.html',
                'trustee'  => 'https://www.mcnairycountytn.org/trustees-office.html',
                'register' => 'https://www.mcnairycountytn.org/register-of-deeds.html',
                'chancery' => 'https://www.mcnairycountytn.org/chancery.html',
                'circuit'  => 'https://www.mcnairycountytn.org/circuit.html',
                'thda'     => $thda,
            ],
            'Meigs' => [
                'assessor' => 'https://www.meigscounty.org/directory-pages/assessor-of-property',
                'trustee'  => 'https://www.meigscounty.org/directory-pages/county-trustee',
                'register' => 'https://www.meigscounty.org/directory-pages/register-of-deeds',
                'chancery' => 'https://www.meigscounty.org/law-justice/clerk-master',
                'circuit'  => 'https://www.meigscounty.org/law-justice/circuit-court-clerk',
                'thda'     => $thda,
            ],
            'Monroe' => [
                'assessor' => 'https://monroetn.gov/monroe-county-property-assessor/',
                'trustee'  => 'https://monroe.tennesseetrustee.org/',
                'register' => 'https://monroetn.gov/monroe-county-register-of-deeds/',
                'chancery' => 'https://monroetn.gov/judicial/',
                'circuit'  => 'https://www.monroecircuitcourt.com/',
                'thda'     => $thda,
            ],
            'Montgomery' => [
                'assessor' => 'https://montgomerytn.gov/assessor',
                'trustee'  => 'https://montgomerytn.gov/trustee',
                'register' => 'https://montgomerytn.gov/deeds',
                'chancery' => 'https://montgomerytn.gov/chancery',
                'circuit'  => 'https://montgomerytn.gov/circuit',
                'thda'     => $thda,
            ],
            'Moore' => [
                'assessor' => 'https://metromoorecounty.org/about_us/tax_assessor.php',
                'trustee'  => 'https://metromoorecounty.org/about_us/trustee.php',
                'register' => 'https://metromoorecounty.org/about_us/register_of_deeds.php',
                'chancery' => 'https://metromoorecounty.org/about_us/court_system/clerk___master.php',
                'circuit'  => 'https://metromoorecounty.org/about_us/court_system/circuit_court_clerk.php',
                'thda'     => $thda,
            ],
            'Morgan' => [
                'assessor' => 'https://www.morgancountytn.gov/assessor-of-property/',
                'trustee'  => 'https://www.morgancountytn.gov/trustee/',
                'register' => 'https://www.morgancountytn.gov/register-of-deeds/',
                'chancery' => 'https://www.morgancountytn.gov/clerk-and-master/',
                'circuit'  => 'https://www.morgancountytn.gov/circuit-court-clerk/',
                'thda'     => $thda,
            ],
            'Obion' => [
                'assessor' => 'https://www.obioncountytn.gov/property_assessor.html',
                'trustee'  => 'https://www.obioncountytn.gov/trustee.html',
                'register' => 'https://www.obioncountytn.gov/register_of_deeds.html',
                'chancery' => 'https://www.obioncountytn.gov/clerk_master.html',
                'circuit'  => 'https://www.obioncountytn.gov/circuit_court.html',
                'thda'     => $thda,
            ],
            'Overton' => [
                'assessor' => 'https://overtoncountytn.gov/departments/property-assessor/',
                'trustee'  => 'https://overtoncountytn.gov/overton-county-trustees-office/',
                'register' => 'https://overtoncounty.org/departments/register-of-deeds/',
                'chancery' => 'https://overtoncounty.org/departments/clerk-master/',
                'circuit'  => 'https://overtoncounty.org/departments/circuit-court-clerk/',
                'thda'     => $thda,
            ],
            'Perry' => [
                'assessor' => 'https://gov.perrycountytn.com/elected-officials/property-assessor',
                'trustee'  => 'https://gov.perrycountytn.com/elected-officials/county-trustee',
                'register' => 'https://gov.perrycountytn.com/elected-officials/county-register',
                'chancery' => 'https://courts.perrycountytn.com/courts/chancery-court-clerk',
                'circuit'  => 'https://courts.perrycountytn.com/courts/circuit-court-clerk',
                'thda'     => $thda,
            ],
            'Pickett' => [
                'assessor' => 'https://dalehollow.com/officials/',
                'trustee'  => 'https://dalehollow.com/officials/',
                'register' => 'https://dalehollow.com/officials/',
                'chancery' => 'https://dalehollow.com/officials/',
                'circuit'  => 'https://dalehollow.com/officials/',
                'thda'     => $thda,
            ],
            'Polk' => [
                'assessor' => 'https://www.polkgovernment.com/property-assess.php',
                'trustee'  => 'https://www.polkgovernment.com/trustee.php',
                'register' => 'https://www.polkgovernment.com/register-deeds.php',
                'chancery' => 'https://www.polkgovernment.com/chancery-court.php',
                'circuit'  => 'https://www.polkgovernment.com/clerk-court.php',
                'thda'     => $thda,
            ],
            'Putnam' => [
                'assessor' => 'https://putnamcountytn.gov/property-assessor',
                'trustee'  => 'https://putnamcountytn.gov/trustee',
                'register' => 'https://putnamcountytn.gov/register-deeds',
                'chancery' => 'https://putnamcountytn.gov/clerk-and-master',
                'circuit'  => 'https://putnamcountytn.gov/circuit-court-clerk',
                'thda'     => $thda,
            ],
            'Rhea' => [
                'assessor' => 'https://rheacountytn.org/departments/',
                'trustee'  => 'https://rheacountytn.org/departments/',
                'register' => 'https://rheacountytn.org/departments/',
                'chancery' => 'https://rheacountytn.gov/rhea-county-courts/',
                'circuit'  => 'https://rheacountytn.gov/rhea-county-courts/',
                'thda'     => $thda,
            ],
            'Roane' => [
                'assessor' => 'https://roanecountytn.gov/assessor-of-property/',
                'trustee'  => 'https://roanecountytn.gov/trustee/',
                'register' => 'https://roanecountytn.gov/register-of-deeds/',
                'chancery' => 'https://roanecountytn.gov/clerk-and-master/',
                'circuit'  => 'https://roanecountytn.gov/circuit-court-clerk/',
                'thda'     => $thda,
            ],
            'Robertson' => [
                'assessor' => 'https://www.robertsoncountytn.gov/local_government/assessor_of_property.php',
                'trustee'  => 'https://robertsoncountytn.gov/local_government/trustee/index.php',
                'register' => 'https://robertsoncountytn.gov/local_government/register_of_deeds/index.php',
                'chancery' => 'https://robertsoncountytn.gov/departments/clerk_and_master/index.php',
                'circuit'  => 'https://robertsoncountytn.gov/local_government/circuit_court_clerk/index.php',
                'thda'     => $thda,
            ],
            'Rutherford' => [
                'assessor' => 'https://rcpatn.com/',
                'trustee'  => 'https://rctrustee.com/',
                'register' => 'https://rutherfordcountytn.gov/register-deeds',
                'chancery' => 'https://rcchancery.com/',
                'circuit'  => 'https://circuitcourtclerk.rutherfordcountytn.gov/',
                'thda'     => $thda,
            ],
            'Scott' => [
                'assessor' => 'https://scottcounty.com/government/assessor-of-property/',
                'trustee'  => 'https://scottcounty.com/government/county-trustee/',
                'register' => 'https://scottcounty.com/government/register-of-deeds/',
                'chancery' => 'https://scottcounty.com/government/chancery-court/',
                'circuit'  => 'https://scottcounty.com/government/circuit-court/',
                'thda'     => $thda,
            ],
            'Sequatchie' => [
                'assessor' => 'https://sequatchiecountytn.gov/directory/government/assessor-of-property/',
                'trustee'  => 'https://sequatchiecountytn.gov/directory/government/county-trustee/',
                'register' => 'https://sequatchiecountytn.gov/directory/government/register-of-deeds/',
                'chancery' => 'https://sequatchiecountytn.gov/directory/courts-law-enforcement/clerk-and-master/',
                'circuit'  => 'https://sequatchiecountytn.gov/directory/courts-law-enforcement/circuit-court-clerk/',
                'thda'     => $thda,
            ],
            'Sevier' => [
                'assessor' => 'https://www.seviercountytn.gov/government/county_officials/property_assessor.php',
                'trustee'  => 'https://www.seviercountytn.gov/government/county_officials/county_trustee/index.php',
                'register' => 'https://www.seviercountytn.gov/government/county_officials/register_of_deeds.php',
                'chancery' => 'https://www.seviercountytn.gov/government/county_officials/clerk___master.php',
                'circuit'  => 'https://www.seviercountytn.gov/government/county_officials/circuit_court_clerk.php',
                'thda'     => $thda,
            ],
            'Shelby' => [
                'assessor' => 'https://www.shelbycountytn.gov/68/Assessor-of-Property',
                'trustee'  => 'https://www.shelbycountytrustee.com/',
                'register' => 'https://register.shelby.tn.us/',
                'chancery' => 'https://www.shelbycountytn.gov/332/The-Clerk-Master',
                'circuit'  => 'https://www.shelbycountytn.gov/338/Circuit-Court-Clerk',
                'thda'     => $thda,
            ],
            'Smith' => [
                'assessor' => 'https://smithcotn.com/property-assessor/',
                'trustee'  => 'https://smithcotn.com/trustee/',
                'register' => 'https://smithcotn.com/register-of-deeds/',
                'chancery' => 'https://smithcotn.com/clerk-and-master/',
                'circuit'  => 'https://smithcotn.com/circuit-court-clerk/',
                'thda'     => $thda,
            ],
            'Stewart' => [
                'assessor' => 'https://www.stewartcogov.com/elected_officials/full_info/mwallace.html',
                'trustee'  => 'https://www.stewartcogov.com/elected_officials/elected_officials.html',
                'register' => 'https://www.stewartcogov.com/elected_officials/elected_officials.html',
                'chancery' => 'https://www.stewartcogov.com/elected_officials/full_info/aturner.html',
                'circuit'  => 'https://www.stewartcogov.com/elected_officials/elected_officials.html',
                'thda'     => $thda,
            ],
            'Sullivan' => [
                'assessor' => 'https://sullivancountytn.gov/property-assessor/',
                'trustee'  => 'https://sullivantntrustee.gov/',
                'register' => 'https://sullivandeeds.com/',
                'chancery' => 'https://www.sullivantnchancery.com/',
                'circuit'  => 'https://sullivancountytn.gov/circuit-court/',
                'thda'     => $thda,
            ],
            'Sumner' => [
                'assessor' => 'https://sumnercountytn.gov/departments/assessor-of-property/',
                'trustee'  => 'https://sumnercountytn.gov/departments/trustee/',
                'register' => 'https://sumnercountytn.gov/departments/register-of-deeds/',
                'chancery' => 'https://sumnerchancerycourt.com/',
                'circuit'  => 'https://sumnercourts.com/',
                'thda'     => $thda,
            ],
            'Tipton' => [
                'assessor' => 'https://tiptonco.com/government/property_assessor/index.php',
                'trustee'  => 'https://www.tiptonco.com/government/trustee/',
                'register' => 'https://tiptonco.com/government/register_of_deeds/index.php',
                'chancery' => 'https://tiptonco.com/government/courts/chancery/index.php',
                'circuit'  => 'https://tiptonco.com/government/courts/circuit/index.php',
                'thda'     => $thda,
            ],
            'Trousdale' => [
                'assessor' => 'https://www.trousdalecountytn.gov/government/county_officials/assessor_of_property.php',
                'trustee'  => 'https://www.trousdalecountytn.gov/government/county_officials/trustee/index.php',
                'register' => 'https://www.trousdalecountytn.gov/government/county_officials/register_of_deeds/index.php',
                'chancery' => 'https://www.trousdalecountytn.gov/government/county_officials/clerk_and_master.php',
                'circuit'  => 'https://www.trousdalecountytn.gov/government/courts___legal/circuit_court_clerk.php',
                'thda'     => $thda,
            ],
            'Unicoi' => [
                'assessor' => 'https://unicoicountytn.com/assessor-of-property/',
                'trustee'  => 'https://unicoicountytn.com/trustee/',
                'register' => 'https://unicoiregister.com/',
                'chancery' => 'https://unicoicountytn.com/clerk-and-master/',
                'circuit'  => 'https://unicoicountytn.com/circuit-court-clerk/',
                'thda'     => $thda,
            ],
            'Union' => [
                'assessor' => 'https://www.unioncountytn.gov/assessor-of-property/',
                'trustee'  => 'https://www.unioncountytn.gov/trustee/',
                'register' => 'https://www.unioncountytn.gov/register-of-deeds/',
                'chancery' => 'https://www.unioncountytnclerkandmaster.com/',
                'circuit'  => 'https://www.unioncountytncourts.com/',
                'thda'     => $thda,
            ],
            'Van Buren' => [
                'assessor' => 'https://vanburencountytn.com/elected_officials/',
                'trustee'  => 'https://www.vanburen.tennesseetrustee.org/',
                'register' => 'https://vanburencountytn.com/elected_officials/',
                'chancery' => 'https://vanburencountytn.com/dept_services/index.html',
                'circuit'  => 'https://vanburencountytn.com/elected_officials/',
                'thda'     => $thda,
            ],
            'Warren' => [
                'assessor' => 'https://www.warrencountytn.gov/government/property_assessor/index.php',
                'trustee'  => 'https://www.warrencountytn.gov/government/new_page/index.php',
                'register' => 'https://www.warrencountytn.gov/government/register_of_deeds/index.php',
                'chancery' => 'https://www.warrenchancery.org/',
                'circuit'  => 'https://www.warrencountytn.gov/government/courts/circuit_court.php',
                'thda'     => $thda,
            ],
            'Washington' => [
                'assessor' => 'https://www.washingtoncountytn.org/233/Property-Assessor',
                'trustee'  => 'https://www.washingtoncountytn.org/243/Trustee',
                'register' => 'https://www.washingtoncountytn.org/230/Register-of-Deeds',
                'chancery' => 'https://www.washingtoncountytn.org/264/Chancery-Court',
                'circuit'  => 'https://www.washingtoncountytn.org/267/Circuit-Court',
                'thda'     => $thda,
            ],
            'Wayne' => [
                'assessor' => 'https://www.waynecountytn.org/offices/index.php',
                'trustee'  => 'https://www.waynecountytn.org/offices/index.php',
                'register' => 'https://www.waynecountytn.org/offices/index.php',
                'chancery' => 'https://www.waynecountytn.org/offices/index.php',
                'circuit'  => 'https://www.waynecountytn.org/offices/index.php',
                'thda'     => $thda,
            ],
            'Weakley' => [
                'assessor' => 'https://www.weakleycountytn.gov/property-assessor.html',
                'trustee'  => 'https://www.weakleycountytn.gov/trustee.html',
                'register' => 'https://www.weakleycountytn.gov/registerofdeeds.html',
                'chancery' => 'https://www.weakleycountytn.gov/clerkandmaster.html',
                'circuit'  => 'https://www.weakleycountytn.gov/circuit-court.html',
                'thda'     => $thda,
            ],
            'White' => [
                'assessor' => 'https://whitecountytn.gov/government/county-offices/assessor-property',
                'trustee'  => 'https://whitecountytn.gov/government/county-offices/county-trustee',
                'register' => 'https://whitecountytn.gov/government/county-offices/register-deeds',
                'chancery' => 'https://whitecountytn.gov/government/county-departments/court-system',
                'circuit'  => 'https://whitecountytn.gov/government/county-offices/circuit-court-clerk',
                'thda'     => $thda,
            ],
            'Williamson' => [
                'assessor' => 'https://www.williamsoncounty-tn.gov/64/Property-Assessor',
                'trustee'  => 'https://www.williamsoncounty-tn.gov/2194/Trustee',
                'register' => 'https://www.williamsoncounty-tn.gov/61/Register-of-Deeds',
                'chancery' => 'https://www.williamsonchancery.org/',
                'circuit'  => 'https://www.williamsoncounty-tn.gov/243/Circuit-Court-Clerk',
                'thda'     => $thda,
            ],
            'Wilson' => [
                'assessor' => 'https://www.wilsoncountytn.gov/301/Property-Assessor',
                'trustee'  => 'https://wilsoncountytn.gov/201/Trustee',
                'register' => 'https://www.wilsondeeds.com/',
                'chancery' => 'https://wilcoclerkandmaster.com/',
                'circuit'  => 'https://wilsoncountycourts.com/',
                'thda'     => $thda,
            ],
        ];
    }

    if ( isset( $data[ $county_key ] ) ) {
        return $data[ $county_key ];
    }

    return [];
}
