<?php
/**
 * Template Name: Foreclosure - Gallatin
 */
$fc_city_name   = 'Gallatin';
$fc_city_slug   = 'gallatin';
$fc_county      = 'Sumner';
$fc_county_slug = 'sumner-county';
$fc_meta_title  = 'Facing Foreclosure in Gallatin TN | Tennessee Cash For Homes';
$fc_meta_desc   = 'Stop foreclosure on your Gallatin TN home near Old Hickory Lake. We buy Sumner County houses fast for cash with no repairs needed and no closing costs to you.';
$fc_courthouse  = 'the Sumner County Courthouse in Gallatin';
$fc_local_desc_1 = 'Gallatin serves as the county seat of Sumner County and has grown from a quiet lakeside town into one of the Nashville metro\'s most popular suburban destinations. Neighborhoods around Old Hickory Lake, the historic downtown square, and the Indian Lake retail corridor have attracted steady waves of new residents over the past two decades. But growth does not shield homeowners from financial hardship. Rising property tax assessments driven by Sumner County\'s booming real estate market have caught many long-time Gallatin residents off guard, and those living on fixed incomes or dealing with job transitions can find themselves unable to keep up. Foreclosure proceedings at the Sumner County Courthouse happen right here in Gallatin, and the public nature of the process can feel especially difficult in a community where neighbors know each other.';
$fc_local_desc_2 = 'Gallatin\'s economy benefits from a mix of healthcare, education, and retail employers. Volunteer State Community College anchors the educational landscape and brings students and staff into the local economy, while the Indian Lake shopping area and Nashville Pike commercial corridor provide retail and service jobs. However, many Gallatin residents commute to Nashville for work, and the rising cost of fuel and vehicle maintenance adds to household budgets that are already stretched thin. Lakefront and lake-adjacent properties near Old Hickory Lake can carry premium price tags and correspondingly higher mortgages, making them especially vulnerable when household income drops. Even homes farther from the water in established neighborhoods off Main Street and Albert Gallatin Avenue face pressure as insurance costs rise and deferred maintenance accumulates over the years.';
$fc_local_desc_3 = 'Tennessee Cash For Homes works with Gallatin homeowners at every stage of the foreclosure process, from the first missed payment notice to the weeks before a scheduled courthouse auction. Because Gallatin is the Sumner County seat, foreclosure sales happen locally, and the timeline can move faster than homeowners expect. We provide fair cash offers on homes throughout Gallatin, whether you own a lakefront property on Old Hickory Lake, a home in one of the subdivisions near Indian Lake, or a fixer-upper closer to downtown. There are no agent commissions, no repair requirements, and no waiting for buyer financing to come through. Our goal is to give you a straightforward option that lets you resolve your mortgage situation, protect your credit score, and move forward with dignity and cash in hand.';
include( get_template_directory() . '/foreclosure-template.php' );
