<?php
/**
 * Template Name: Foreclosure - Lebanon
 */
$fc_city_name   = 'Lebanon';
$fc_city_slug   = 'lebanon';
$fc_county      = 'Wilson';
$fc_county_slug = 'wilson-county';
$fc_meta_title  = 'Facing Foreclosure in Lebanon TN | Tennessee Cash For Homes';
$fc_meta_desc   = 'Facing foreclosure in Lebanon TN? We buy Wilson County homes for cash fast. No repairs, no commissions, and no waiting. Get a fair offer and close on your schedule.';
$fc_courthouse  = 'the Wilson County Courthouse in Lebanon';
$fc_local_desc_1 = 'Lebanon is the county seat of Wilson County and a city that has experienced tremendous growth as Nashville\'s eastern suburbs have expanded along the I-40 corridor. Once known primarily for the Wilson County Fair and Cumberland University, Lebanon has become a destination for families and businesses seeking more space and lower costs than what Nashville offers. But this growth wave has created financial vulnerability for many homeowners. Those who purchased during peak market conditions may now carry mortgages that strain their budgets, while long-time residents face property tax increases driven by new development in the Providence area and along South Hartmann Drive. When income disruptions occur, the path to foreclosure at the Wilson County Courthouse can happen faster than many Lebanon homeowners realize.';
$fc_local_desc_2 = 'Lebanon\'s economic landscape has diversified significantly in recent years. The arrival of Amazon\'s distribution center and other logistics operations along the I-40 corridor has created thousands of jobs, but many of these positions offer hourly wages that may not keep pace with the rising cost of homeownership in Wilson County. Cumberland University provides educational opportunities and campus-related employment, while the historic downtown square supports a growing collection of small businesses and restaurants. The Wilson County Fairgrounds remain a cultural anchor, hosting events that draw visitors from across the region. However, the rapid pace of construction in areas like Providence and along Lebanon Road has not necessarily lifted property values uniformly across the city. Homeowners in older neighborhoods near Castle Heights and along Greenwood Avenue may find their homes are worth less than expected, complicating efforts to refinance or sell when foreclosure threatens.';
$fc_local_desc_3 = 'Tennessee Cash For Homes offers Lebanon homeowners a straightforward way to avoid foreclosure and protect their financial future. We buy houses throughout Lebanon and Wilson County in any condition, from established homes near the downtown square and Cumberland University to newer properties in the Providence development area and beyond. Because Lebanon is the Wilson County seat, foreclosure auctions happen locally on the courthouse steps, and the public visibility of the process adds urgency for homeowners who want to resolve the situation privately. We move quickly, providing a cash offer within days and closing on a timeline that works for you. There are no realtor commissions, no repair requirements, and no hidden fees. If you are behind on your mortgage or have received a foreclosure notice, talking to us early gives you the best chance to walk away with cash and your credit intact.';
include( get_template_directory() . '/foreclosure-template.php' );
